### PR TITLE
Auto download youtube-dl if not present

### PR DESCRIPTION
**Pull request by PierreSchwang**
Could be buggy on windows tho

### CODE REVIEW

**Comment by freggy** [comment]
Downloading the youtube-dl executable should not be the responsibility of the application. The operator should take care of that, but I think there should be a cli option to specify the path to the executable. Maybe we should provide a Dockerfile which has youtube-dl pre-installed. Would be nice if you could add that :)

**Comment by freggy** [comment]
Any updates on this?

**Comment by PierreSchwang** [comment]
Didn't had the time yet, but I could try today - Should the Dockerfile be built automatically via actions?

**Comment by PierreSchwang** [comment]
Moved to #2 due to hard reset to be even with your repository and keep things sorta organized

**Pull request closed without merging**
